### ISSUE TITLE
Importar FXCC por plantas

### ISSUE THREAD

**Issue by raulfarnanz** [yeahmike/sec4qgis#1]
Me gustaría saber si va a ser posible importar FXCC por plantas de forma masiva creando shapes por plantas con sus geometrías

raulfarnanz@gmail.com

**Comment by yeahmike** [comment]
Perdón por responder con tanto retraso, pero no recibí ninguna notificación de que se hubiera abierto esta incidencia.

Los FXCC por plantas describen la geometría de las construcciones (de cada planta de éstas), pero actualmente SEC4QGIS solo importa y exporta parcelas catastrales.
