### ISSUE TITLE
No importa cartografia catastral en Ubuntu, Lubunti, Opensuse

### ISSUE THREAD

**Issue by Antr0** [yeahmike/sec4qgis#3]
![captura de pantalla 2017-11-05 18 49 51](https://user-images.githubusercontent.com/33399498/32417538-6c094b42-c25b-11e7-806c-f031f30aef3e.png)
Hola, 
He intentado importar la cartografía catastral en Ubuntu 17.10 con la version de Qgis 2.14.18 Essen y no me permite importar nada, no reconoce los archivos .zip ni los dxf obtenidos de la sede de catastro.

Con la version 2.18 Las Palmas he probado tanto en Opensuse Tumbleweed como en Lubuntu 17.04, con el mismo resultado. Pincho en importar cartografía catastral busco en las carpetas en las que estas se encuentra y no encuentra ni el zip ni los dxf.

Esto mismo en windows 7 con la version 2.18 de Qgis y en las mismas carpetas lo he realizado sin problema alguno.

No se si es un bug o un problema mío, pero he probado en tres ordenadores distintos y en 3 SO distintos (sin contar Windows). Incluso he probado a meter la direccion del archivo en la barra de direcciones con los mismos resultados

La version del plugin que empleo en todos los casos es la 1.0.4

Muchisimas gracias por tu trabajo

**Comment by yeahmike** [comment]
Efectivamente, hay varios fallos en el manejo de ficheros en GNU/Linux, por lo que he actualizado el repositorio no oficial (http://sec4qgis.tk/plugins.php) con una versión (la 1.0.5) que funciona en Ubuntu 17.10 y QGIS 2.18.14 Las Palmas. Probablemente sepas cómo añadir repositorios adicionales en QGIS, aunque también lo explico en el apartado 2.2.1 del manual del complemento.

Antes de actualizar el repo oficial y GitHub, ¿puedes confirmarme si la versión 1.0.5 te funciona a ti también? 

Gracias.

**Comment by Antr0** [comment]
Hola,

Perfecto. Lo he probado en Ubuntu Mate 17.04  con Qgis 2.14.11 Essen y me
ha funcionado sin problemas.

Muchísimas gracias. Ya tenía ganas de poder hacer un trabajo técnico
integramente con software libre y de una forma tan sencilla.
